# Generated by Django 4.2.20 on 2025-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_userdetails_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
