# Generated by Django 4.2.20 on 2025-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avatar',
            field=models.ImageField(blank=True, default='img/log_in.png', null=True, upload_to='avatars/'),
        ),
    ]
