# Generated by Django 4.2.20 on 2025-06-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0019_dailynutrition_burned_extra_calories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BurnedCaloriesVideo',
        ),
    ]
